function(add_unit_test name source)
    add_executable(${name} ${source})
    target_link_libraries(${name} PRIVATE unity)
    target_compile_options(${name} PRIVATE --coverage)
    target_link_options(${name} PRIVATE --coverage)
    add_test(NAME ${name} COMMAND ${name})
endfunction()

add_unit_test(TestRange TestRange.c)
add_executable(TestASCII TestASCII.c ../src/ASCII.c)
target_link_libraries(TestASCII PRIVATE unity)
target_compile_options(TestASCII PRIVATE --coverage)
target_link_options(TestASCII PRIVATE --coverage)
add_test(NAME TestASCII COMMAND TestASCII)

add_executable(TestSafeStrings TestSafeStrings.c ../src/SafeStrings.c ../src/ASCII.c)
target_link_libraries(TestSafeStrings PRIVATE unity)
target_compile_options(TestSafeStrings PRIVATE --coverage)
target_link_options(TestSafeStrings PRIVATE --coverage)
add_test(NAME TestSafeStrings COMMAND TestSafeStrings)

add_executable(TestParseNumbers TestParseNumbers.c ../src/ParseNumbers.c)
target_link_libraries(TestParseNumbers PRIVATE unity)
target_compile_options(TestParseNumbers PRIVATE --coverage)
target_link_options(TestParseNumbers PRIVATE --coverage)
add_test(NAME TestParseNumbers COMMAND TestParseNumbers)
